name: SmartBear Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  schedule:
    - cron: "0 12 * * *"

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    name: "Testing ${{ matrix.project }} (${{ matrix.shardIndex }} / ${{ matrix.shardTotal }})"
    strategy:
      fail-fast: false
      matrix:
        include:
          - project: SmartBear E2E Tests - Chrome
            testDir: tests/e2e-tests
          - project: SmartBear Setup Tests
            testDir: tests/setup
          - project: SmartBear Authentication Test
            testDir: tests/login-tests
        shardIndex: [1, 2, 3]
        shardTotal: [3]
    env:
      baseURL: ${{ vars.BASEURL }}
      loginURL: ${{ vars.LOGINURL }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        # run: npx playwright test --project=${{ matrix.project }} --shard=${{ matrix.shardIndex }} / ${{ matrix.shardTotal }}
        # run: npx playwright test tests/e2e-tests
        run: npx playwright test --project="${{ matrix.project }}" --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}
      - name: Upload Playwright report
        if: ${{ !cancelled() && matrix.project != 'SmartBear Setup Tests' }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ matrix.project }}-${{ matrix.shardIndex }}
          path: playwright-report/
          retention-days: 30
      # - name: Upload Playwright report
      #   uses: actions/upload-artifact@v4
      #   if: ${{ !cancelled() }}
      #   with:
      #     # name: playwright-report-${{ matrix.project }}-${{ matrix.shardIndex }}
      #     name: playwright-report
      #     path: playwright-report/
      #     retention-days: 30
